### ISSUE TITLE
Refactor Request Media Parsers

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim-Http#4]
Should these be moved to a static registry inside the Request class? This would make it easier to inject custom parsers... e.g., `\Slim\Http\Request::addParser('text/csv', function ($input) { ... });`

**Comment by geggleto** [comment]
I don't think a static registry makes a lot of sense.
Every request object could have 1 or more different types of parsers.

I am thinking when I use Slim with ReactPHP it would be way more beneficial for me to register a parser on an instance of the request object rather than on the whole domain of request objects.

**Comment by geggleto** [comment]
@codeguy https://github.com/geggleto/input-parser

**Comment by geekish** [comment]
You might also want to have a look at how [Equip](//github.com/equip/framework) does this via middleware. :)

**Comment by geggleto** [comment]
@geekish they do it via  zend-diactoros

**Comment by geggleto** [comment]
Found this interesting as well.

https://github.com/PatrickLouys/http

**Comment by geekish** [comment]
@geggleto I was referring to their ContentHandler middlewares.

**Comment by geggleto** [comment]
@geekish oh! :) my bad

**Comment by akrabat** [comment]
I don't think we need this.
